
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Basic Cloudfront distribution with an S3 origin used for HTAN static webassets'

Parameters:
  S3BucketName:
    Type: String
    Default: Your S3 Bucket Name
    Description: Name of existing S3 bucket
  S3LoggingBucketName:
    Type: String
    Default: Your S3 Bucket Name For Logging
    Description: Name of existing S3 bucket
  OAIEnabled:
    Type: String
    Default: "no"
    AllowedValues: ["yes", "no"]
    Description: Enable OAI (Access to bucket only through CloudFront)

Conditions:
  WithOAIEnabled: !Equals [!Ref "OAIEnabled", "yes"]
  WithOutOAIEnabled: !Equals [!Ref "OAIEnabled", "no"]

Resources:
  S3BucketPolicyWithAOI:
    Type: 'AWS::S3::BucketPolicy'
    Metadata: 
      Comment: 'Bucket  policy to allow cloudfront to access the data'
    Condition: WithOAIEnabled
    Properties:
      Bucket: !Ref S3BucketName
      PolicyDocument:
        Statement:
          - Action:
              - 's3:GetObject'
            Effect: 'Allow'
            Principal:
              CanonicalUser: !GetAtt CfOriginAccessIdentity.S3CanonicalUserId
            Resource:
              - !Sub 'arn:aws:s3:::${S3BucketName}/*'

  CfDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Condition: WithOutOAIEnabled
    Metadata: 
      Comment: 'A simple CloudFront distribution with an S3 origin' 
    Properties:
      DistributionConfig:
        Comment: 'A simple distribution with an S3 origin'
        DefaultCacheBehavior:
          AllowedMethods:
            - 'HEAD'
            - 'GET'
          CachedMethods:
            - 'HEAD'
            - 'GET'
          Compress: true
          DefaultTTL: 86400 # deprecated, use DefaultTTL in a cache policy instead
          ForwardedValues: # deprecated, use a cache policy or an origin request policy instead
            Cookies:
              Forward: 'none'
            Headers:
              - 'Origin'
            QueryString: false
          MaxTTL: 31536000 # 365 days
          MinTTL: 86400 # 1 day
          TargetOriginId: !Sub 's3-origin-${S3BucketName}'
          ViewerProtocolPolicy: 'redirect-to-https'
        DefaultRootObject: 'index.html'
        Enabled: true
        HttpVersion: 'http2'
        IPV6Enabled: false
        Origins:
          - DomainName: !Sub '${S3BucketName}.s3.amazon.aws.com'
            Id: !Sub 's3-origin-${S3BucketName}'
            S3OriginConfig: {}
        Logging:
          Bucket: !Sub '${S3LoggingBucketName}.s3.amazonaws.com'
          IncludeCookies: false
          Prefix: 'htan-portal-cdn'
        PriceClass: 'PriceClass_All'

  CfDistributionWithAOI:
    Type: 'AWS::CloudFront::Distribution'
    Condition: WithOAIEnabled
    Metadata: 
      Comment: 'A simple CloudFront distribution with an S3 origin' 
    Properties:
      DistributionConfig:
        Comment: 'A simple distribution with an S3 origin'
        DefaultCacheBehavior:
          AllowedMethods:
            - 'HEAD'
            - 'GET'
          CachedMethods:
            - 'HEAD'
            - 'GET'
          Compress: true
          DefaultTTL: 86400 # deprecated, use DefaultTTL in a cache policy instead
          ForwardedValues: # deprecated, use a cache policy or an origin request policy instead
            Cookies:
              Forward: 'none'
            Headers:
              - 'Origin'
            QueryString: false
          MaxTTL: 31536000 # 365 days
          MinTTL: 86400 # 1 day
          TargetOriginId: !Sub 's3-origin-${S3BucketName}'
          ViewerProtocolPolicy: 'redirect-to-https'
        DefaultRootObject: 'index.html'
        Enabled: true
        HttpVersion: 'http2'
        IPV6Enabled: false
        Origins:
          - DomainName: !Sub '${S3BucketName}.s3.amazonaws.com'
            Id: !Sub 's3-origin-${S3BucketName}'
            OriginPath: ''
            S3OriginConfig: 
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CfOriginAccessIdentity}'
        Logging:
          Bucket: !Sub '${S3LoggingBucketName}.s3.amazonaws.com'
          IncludeCookies: false
          Prefix: 'htan-portal-cdn'
        PriceClass: 'PriceClass_All'

  CfOriginAccessIdentity:
    Type: 'AWS::CloudFront::CloudFrontOriginAccessIdentity'
    Condition: WithOAIEnabled
    Metadata:
      Comment: 'Access S3 bucket content only through CloudFront'
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: 'Access S3 bucket content only through CloudFront'


Outputs:
  S3BucketName:
    Description: 'Bucket name'
    Value: !Ref S3BucketName
  S3LoggingBucketName:
    Description: 'Bucket name assigned for logging'
    Value: !Ref S3LoggingBucketName
  CfDistributionWithOAI:
    Description: 'Id for our cloudfront distribution'
    Value: !Ref CfDistributionWithAOI
    Condition: WithOAIEnabled
  CfDistributionId:
    Description: 'Id for our cloudfront distribution'
    Value: !Ref CfDistribution
    Condition: WithOutOAIEnabled
  CfDistributionDomainNameWithOAI:
    Description: 'Domain name for our cloudfront distribution'
    Value: !GetAtt CfDistributionWithAOI.DomainName
    Condition: WithOAIEnabled
  CfDistributionDomainName:
    Description: 'Domain name for our cloudfront distribution'
    Value: !GetAtt CfDistribution.DomainName
    Condition: WithOutOAIEnabled

