name: aws-deploy

on: push

jobs:
  pre-commit:
    name: Run pre-commit hooks against all files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v2.0.2

  sceptre-deploy:
    name: Deploy CloudFormation templates using sceptre
    runs-on: ubuntu-latest
    needs: pre-commit
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Assume AWS role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CI_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.CI_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::888810830951:role/htan-dev-ci-service-account-ServiceRole-1I0ERPZD8ZKDS
          role-duration-seconds: 1200
      - name: Create directory for remote sceptre templates
        run: mkdir -p templates/remote/
      - name: Deploy 'dev' configuration
        uses: Sceptre/github-ci-action@v2.3.0
        with:
          sceptre_version: '4.5.2'
          sceptre_subcommand: launch --yes dev
